### ISSUE TITLE
java.lang.Boolean cannot be cast to java.lang.String -- Phrasal.java:1213

### ISSUE THREAD

**Issue by chrishokamp** [stanfordnlp/phrasal#1]
hi all thanks for the awesome work!

i was trying to run the webservice, which I successfully did after changing 759bb651103e71cc359c5703e6200c02e98d69d8 back to what it was before. the problem stems from [this line](https://github.com/stanfordnlp/phrasal/blob/master/src-extra/edu/stanford/nlp/mt/service/handlers/TranslationRequestHandler.java#L170), where the property is set as a Boolean. Is there some other reason you changed it, or a different way to run the webservice? 

The full error:
```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at edu.stanford.nlp.mt.Phrasal.decode(Phrasal.java:1213) ~[phrasal-3.4.1.jar:3.4.1]
        at edu.stanford.nlp.mt.service.handlers.TranslationRequestHandler$DecoderService.process(TranslationRequestHandler.java:177) [phrasal-3.4.1.jar:3.4.1]
        at edu.stanford.nlp.mt.service.handlers.TranslationRequestHandler$DecoderService.process(TranslationRequestHandler.java:117) [phrasal-3.4.1.jar:3.4.1]
        at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:249) [stanford-corenlp-3.5.2.jar:3.5.2]
        at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:230) [stanford-corenlp-3.5.2.jar:3.5.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

my test query, which works once I revert 759bb651103e71cc359c5703e6200c02e98d69d8
(I built a Spanish --> English system)
```
http://127.0.0.1:8017/x?tReq={"src":"ES", "tgt":"EN", "text": "el parlamento de ucrania", "tgtPrefix":"ukraine", "n": 6}
```

**Comment by chrishokamp** [comment]
looks like you fixed this in cc94538b7ed1d932169e91442168a3c41bfe370a
